import type { Metadata } from "next";
import { Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";
import HeartComponent from "@/components/UI/Heart";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${nunito.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className="min-h-screen flex flex-col relative">
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>

          <Navbar />
          <section className="mt-4 flex flex-1 items-stretch gap-x-16 wrapper ">

            <section className="w-[35%] h-full">
              <HeartComponent />
            </section>
            <section className="w-[65%] flex flex-col">
              {children}
            </section>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
